### ISSUE TITLE
README specifies non-existent bin dir

### ISSUE THREAD

**Issue by mi5key** [newrelic/nri-vmware-esxi#1]
The README specifies a bin directory

cp -R bin /var/db/newrelic-infra/custom-integrations/

The src directory contains the .go files but no bin directory for executables.  Do we need to compile these ourselves?

**Comment by preddy-newrelic** [comment]
You should either build it yourself Or download the latest prebuilt binary from the releases area (https://github.com/newrelic/nri-vmware-esxi/releases)
